version: '3.3'
services:
  back-end-service:
    build: ./back-end/
    ports:
      - 5000:80
      - 5001:5039
      - 7275:7275
    networks:
      - mongo-compose-network
    environment:
      AI_HOST: https://api.openai.com/v1/completions
      AI_KEY: INSERT_API_KEY
      KEYCLOACK_REALM: zipchat
      KEYCLOACK_AUTH_SERVER: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}/
      KEYCLOACK_AUTHORITY: https://${DOCKER_GATEWAY_HOST:-host.docker.internal}/auth/realms/zipchat
      KEYCLOACK_SSL_REQUIRED: none
      KEYCLOACK_RESOURCE: zipchat-api
      KEYCLOACK_VERIFY_TOKEN_AUDIENCE: true
      KEYCLOACK_CREDENTIALS_SECRET: apFCRbmwETIKR78F4stVqHQNy3SUhK5O
      KEYCLOACK_CONFIDENTIAL_PORT: 0
      KEYCLOACK_RESPONSE_TYPE: code
      TEST: true
    depends_on:
      - mongo
    volumes: 
      - ./local/appsettings.docker.json:/back-zipchat/appsettings.json
      - ./local/appsettings.docker.json:/app/appsettings.json

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - mongo-compose-network
      
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

  db-keycloack:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - keycloack-db:/var/lib/mysql
    networks:
      - mongo-compose-network
      
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=user
      - KC_DB_PASSWORD=password
      - KC_DB_URL_HOST=db-keycloack
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - db-keycloack
    networks:
      - mongo-compose-network
volumes:
  keycloack-db:
  mongo-db:
networks: 
    mongo-compose-network:
      driver: bridge